// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendDeploymentLog = `-- name: AppendDeploymentLog :one
INSERT INTO deployment_logs (deployment_id, level, message)
VALUES ($1, $2, $3)
RETURNING id, deployment_id, level, message, created_at
`

type AppendDeploymentLogParams struct {
	DeploymentID uuid.UUID `json:"deployment_id"`
	Level        string    `json:"level"`
	Message      string    `json:"message"`
}

func (q *Queries) AppendDeploymentLog(ctx context.Context, arg AppendDeploymentLogParams) (DeploymentLog, error) {
	row := q.db.QueryRow(ctx, appendDeploymentLog, arg.DeploymentID, arg.Level, arg.Message)
	var i DeploymentLog
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Level,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (site_id, status, message, started_at)
VALUES ($1, $2, $3, $4)
RETURNING id, site_id, status, message, started_at, finished_at, created_at
`

type CreateDeploymentParams struct {
	SiteID    uuid.UUID          `json:"site_id"`
	Status    string             `json:"status"`
	Message   string             `json:"message"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.SiteID,
		arg.Status,
		arg.Message,
		arg.StartedAt,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.Message,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, site_id, status, message, started_at, finished_at, created_at FROM deployments WHERE id = $1
`

func (q *Queries) GetDeployment(ctx context.Context, id uuid.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.Message,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDeploymentLogs = `-- name: ListDeploymentLogs :many
SELECT id, deployment_id, level, message, created_at FROM deployment_logs WHERE deployment_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListDeploymentLogs(ctx context.Context, deploymentID uuid.UUID) ([]DeploymentLog, error) {
	rows, err := q.db.Query(ctx, listDeploymentLogs, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentLog{}
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Level,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentLogsAfter = `-- name: ListDeploymentLogsAfter :many
SELECT id, deployment_id, level, message, created_at FROM deployment_logs
WHERE deployment_id = $1 AND id > $2
ORDER BY created_at ASC
`

type ListDeploymentLogsAfterParams struct {
	DeploymentID uuid.UUID `json:"deployment_id"`
	ID           int64     `json:"id"`
}

func (q *Queries) ListDeploymentLogsAfter(ctx context.Context, arg ListDeploymentLogsAfterParams) ([]DeploymentLog, error) {
	rows, err := q.db.Query(ctx, listDeploymentLogsAfter, arg.DeploymentID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploymentLog{}
	for rows.Next() {
		var i DeploymentLog
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Level,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentsBySite = `-- name: ListDeploymentsBySite :many
SELECT id, site_id, status, message, started_at, finished_at, created_at FROM deployments WHERE site_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListDeploymentsBySite(ctx context.Context, siteID uuid.UUID) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsBySite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Status,
			&i.Message,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeployment = `-- name: UpdateDeployment :one
UPDATE deployments SET
    status = COALESCE($1, status),
    message = COALESCE($2, message),
    started_at = COALESCE($3, started_at),
    finished_at = COALESCE($4, finished_at)
WHERE id = $5
RETURNING id, site_id, status, message, started_at, finished_at, created_at
`

type UpdateDeploymentParams struct {
	Status     pgtype.Text        `json:"status"`
	Message    pgtype.Text        `json:"message"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	ID         uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeployment,
		arg.Status,
		arg.Message,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Status,
		&i.Message,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
