// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_env_vars.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteSiteEnvVar = `-- name: DeleteSiteEnvVar :exec
DELETE FROM site_env_vars WHERE site_id = $1 AND key = $2
`

type DeleteSiteEnvVarParams struct {
	SiteID uuid.UUID `json:"site_id"`
	Key    string    `json:"key"`
}

func (q *Queries) DeleteSiteEnvVar(ctx context.Context, arg DeleteSiteEnvVarParams) error {
	_, err := q.db.Exec(ctx, deleteSiteEnvVar, arg.SiteID, arg.Key)
	return err
}

const deleteSiteEnvVars = `-- name: DeleteSiteEnvVars :exec
DELETE FROM site_env_vars WHERE site_id = $1
`

func (q *Queries) DeleteSiteEnvVars(ctx context.Context, siteID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSiteEnvVars, siteID)
	return err
}

const listSiteEnvVars = `-- name: ListSiteEnvVars :many
SELECT id, site_id, key, value, created_at, updated_at FROM site_env_vars WHERE site_id = $1 ORDER BY key ASC
`

func (q *Queries) ListSiteEnvVars(ctx context.Context, siteID uuid.UUID) ([]SiteEnvVar, error) {
	rows, err := q.db.Query(ctx, listSiteEnvVars, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteEnvVar{}
	for rows.Next() {
		var i SiteEnvVar
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSiteEnvVar = `-- name: UpsertSiteEnvVar :one
INSERT INTO site_env_vars (site_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (site_id, key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = now()
RETURNING id, site_id, key, value, created_at, updated_at
`

type UpsertSiteEnvVarParams struct {
	SiteID uuid.UUID `json:"site_id"`
	Key    string    `json:"key"`
	Value  string    `json:"value"`
}

func (q *Queries) UpsertSiteEnvVar(ctx context.Context, arg UpsertSiteEnvVarParams) (SiteEnvVar, error) {
	row := q.db.QueryRow(ctx, upsertSiteEnvVar, arg.SiteID, arg.Key, arg.Value)
	var i SiteEnvVar
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
