// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_domains.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteSiteDomain = `-- name: DeleteSiteDomain :exec
DELETE FROM site_domains WHERE site_id = $1 AND domain = $2
`

type DeleteSiteDomainParams struct {
	SiteID uuid.UUID `json:"site_id"`
	Domain string    `json:"domain"`
}

func (q *Queries) DeleteSiteDomain(ctx context.Context, arg DeleteSiteDomainParams) error {
	_, err := q.db.Exec(ctx, deleteSiteDomain, arg.SiteID, arg.Domain)
	return err
}

const deleteSiteDomains = `-- name: DeleteSiteDomains :exec
DELETE FROM site_domains WHERE site_id = $1
`

func (q *Queries) DeleteSiteDomains(ctx context.Context, siteID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSiteDomains, siteID)
	return err
}

const listSiteDomains = `-- name: ListSiteDomains :many
SELECT id, site_id, domain, is_primary, created_at FROM site_domains WHERE site_id = $1 ORDER BY is_primary DESC, domain ASC
`

func (q *Queries) ListSiteDomains(ctx context.Context, siteID uuid.UUID) ([]SiteDomain, error) {
	rows, err := q.db.Query(ctx, listSiteDomains, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteDomain{}
	for rows.Next() {
		var i SiteDomain
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Domain,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSiteDomain = `-- name: UpsertSiteDomain :one
INSERT INTO site_domains (site_id, domain, is_primary)
VALUES ($1, $2, $3)
ON CONFLICT (site_id, domain) DO UPDATE SET is_primary = EXCLUDED.is_primary
RETURNING id, site_id, domain, is_primary, created_at
`

type UpsertSiteDomainParams struct {
	SiteID    uuid.UUID `json:"site_id"`
	Domain    string    `json:"domain"`
	IsPrimary bool      `json:"is_primary"`
}

func (q *Queries) UpsertSiteDomain(ctx context.Context, arg UpsertSiteDomainParams) (SiteDomain, error) {
	row := q.db.QueryRow(ctx, upsertSiteDomain, arg.SiteID, arg.Domain, arg.IsPrimary)
	var i SiteDomain
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Domain,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}
