// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSite = `-- name: CreateSite :one
INSERT INTO sites (
    name, slug, primary_url, git_repo_url, git_branch,
    dockerfile_path, build_context, container_port, host_port,
    nginx_ssl_enabled, nginx_force_https, site_type,
    docker_volume_mounts, docker_named_volumes, docker_network_host, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, name, slug, primary_url, git_repo_url, git_branch, dockerfile_path, build_context, container_port, host_port, nginx_ssl_enabled, nginx_force_https, site_type, docker_volume_mounts, docker_named_volumes, docker_network_host, status, created_at, updated_at
`

type CreateSiteParams struct {
	Name               string      `json:"name"`
	Slug               string      `json:"slug"`
	PrimaryUrl         string      `json:"primary_url"`
	GitRepoUrl         string      `json:"git_repo_url"`
	GitBranch          string      `json:"git_branch"`
	DockerfilePath     string      `json:"dockerfile_path"`
	BuildContext       string      `json:"build_context"`
	ContainerPort      int32       `json:"container_port"`
	HostPort           pgtype.Int4 `json:"host_port"`
	NginxSslEnabled    bool        `json:"nginx_ssl_enabled"`
	NginxForceHttps    bool        `json:"nginx_force_https"`
	SiteType           string      `json:"site_type"`
	DockerVolumeMounts string      `json:"docker_volume_mounts"`
	DockerNamedVolumes string      `json:"docker_named_volumes"`
	DockerNetworkHost  bool        `json:"docker_network_host"`
	Status             string      `json:"status"`
}

func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.Name,
		arg.Slug,
		arg.PrimaryUrl,
		arg.GitRepoUrl,
		arg.GitBranch,
		arg.DockerfilePath,
		arg.BuildContext,
		arg.ContainerPort,
		arg.HostPort,
		arg.NginxSslEnabled,
		arg.NginxForceHttps,
		arg.SiteType,
		arg.DockerVolumeMounts,
		arg.DockerNamedVolumes,
		arg.DockerNetworkHost,
		arg.Status,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PrimaryUrl,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.DockerfilePath,
		&i.BuildContext,
		&i.ContainerPort,
		&i.HostPort,
		&i.NginxSslEnabled,
		&i.NginxForceHttps,
		&i.SiteType,
		&i.DockerVolumeMounts,
		&i.DockerNamedVolumes,
		&i.DockerNetworkHost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = $1
`

func (q *Queries) DeleteSite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSite, id)
	return err
}

const getSite = `-- name: GetSite :one
SELECT id, name, slug, primary_url, git_repo_url, git_branch, dockerfile_path, build_context, container_port, host_port, nginx_ssl_enabled, nginx_force_https, site_type, docker_volume_mounts, docker_named_volumes, docker_network_host, status, created_at, updated_at FROM sites WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id uuid.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PrimaryUrl,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.DockerfilePath,
		&i.BuildContext,
		&i.ContainerPort,
		&i.HostPort,
		&i.NginxSslEnabled,
		&i.NginxForceHttps,
		&i.SiteType,
		&i.DockerVolumeMounts,
		&i.DockerNamedVolumes,
		&i.DockerNetworkHost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteBySlug = `-- name: GetSiteBySlug :one
SELECT id, name, slug, primary_url, git_repo_url, git_branch, dockerfile_path, build_context, container_port, host_port, nginx_ssl_enabled, nginx_force_https, site_type, docker_volume_mounts, docker_named_volumes, docker_network_host, status, created_at, updated_at FROM sites WHERE slug = $1
`

func (q *Queries) GetSiteBySlug(ctx context.Context, slug string) (Site, error) {
	row := q.db.QueryRow(ctx, getSiteBySlug, slug)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PrimaryUrl,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.DockerfilePath,
		&i.BuildContext,
		&i.ContainerPort,
		&i.HostPort,
		&i.NginxSslEnabled,
		&i.NginxForceHttps,
		&i.SiteType,
		&i.DockerVolumeMounts,
		&i.DockerNamedVolumes,
		&i.DockerNetworkHost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT id, name, slug, primary_url, git_repo_url, git_branch, dockerfile_path, build_context, container_port, host_port, nginx_ssl_enabled, nginx_force_https, site_type, docker_volume_mounts, docker_named_volumes, docker_network_host, status, created_at, updated_at FROM sites ORDER BY created_at DESC
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.Query(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.PrimaryUrl,
			&i.GitRepoUrl,
			&i.GitBranch,
			&i.DockerfilePath,
			&i.BuildContext,
			&i.ContainerPort,
			&i.HostPort,
			&i.NginxSslEnabled,
			&i.NginxForceHttps,
			&i.SiteType,
			&i.DockerVolumeMounts,
			&i.DockerNamedVolumes,
			&i.DockerNetworkHost,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSite = `-- name: UpdateSite :one
UPDATE sites SET
    name = COALESCE($1, name),
    primary_url = COALESCE($2, primary_url),
    git_repo_url = COALESCE($3, git_repo_url),
    git_branch = COALESCE($4, git_branch),
    dockerfile_path = COALESCE($5, dockerfile_path),
    build_context = COALESCE($6, build_context),
    container_port = COALESCE($7, container_port),
    host_port = COALESCE($8, host_port),
    nginx_ssl_enabled = COALESCE($9, nginx_ssl_enabled),
    nginx_force_https = COALESCE($10, nginx_force_https),
    site_type = COALESCE($11, site_type),
    docker_volume_mounts = COALESCE($12, docker_volume_mounts),
    docker_named_volumes = COALESCE($13, docker_named_volumes),
    docker_network_host = COALESCE($14, docker_network_host),
    status = COALESCE($15, status),
    updated_at = now()
WHERE id = $16
RETURNING id, name, slug, primary_url, git_repo_url, git_branch, dockerfile_path, build_context, container_port, host_port, nginx_ssl_enabled, nginx_force_https, site_type, docker_volume_mounts, docker_named_volumes, docker_network_host, status, created_at, updated_at
`

type UpdateSiteParams struct {
	Name               pgtype.Text `json:"name"`
	PrimaryUrl         pgtype.Text `json:"primary_url"`
	GitRepoUrl         pgtype.Text `json:"git_repo_url"`
	GitBranch          pgtype.Text `json:"git_branch"`
	DockerfilePath     pgtype.Text `json:"dockerfile_path"`
	BuildContext       pgtype.Text `json:"build_context"`
	ContainerPort      pgtype.Int4 `json:"container_port"`
	HostPort           pgtype.Int4 `json:"host_port"`
	NginxSslEnabled    pgtype.Bool `json:"nginx_ssl_enabled"`
	NginxForceHttps    pgtype.Bool `json:"nginx_force_https"`
	SiteType           pgtype.Text `json:"site_type"`
	DockerVolumeMounts pgtype.Text `json:"docker_volume_mounts"`
	DockerNamedVolumes pgtype.Text `json:"docker_named_volumes"`
	DockerNetworkHost  pgtype.Bool `json:"docker_network_host"`
	Status             pgtype.Text `json:"status"`
	ID                 uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSite,
		arg.Name,
		arg.PrimaryUrl,
		arg.GitRepoUrl,
		arg.GitBranch,
		arg.DockerfilePath,
		arg.BuildContext,
		arg.ContainerPort,
		arg.HostPort,
		arg.NginxSslEnabled,
		arg.NginxForceHttps,
		arg.SiteType,
		arg.DockerVolumeMounts,
		arg.DockerNamedVolumes,
		arg.DockerNetworkHost,
		arg.Status,
		arg.ID,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PrimaryUrl,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.DockerfilePath,
		&i.BuildContext,
		&i.ContainerPort,
		&i.HostPort,
		&i.NginxSslEnabled,
		&i.NginxForceHttps,
		&i.SiteType,
		&i.DockerVolumeMounts,
		&i.DockerNamedVolumes,
		&i.DockerNetworkHost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteHostPort = `-- name: UpdateSiteHostPort :one
UPDATE sites SET host_port = $2, updated_at = now() WHERE id = $1 RETURNING id, name, slug, primary_url, git_repo_url, git_branch, dockerfile_path, build_context, container_port, host_port, nginx_ssl_enabled, nginx_force_https, site_type, docker_volume_mounts, docker_named_volumes, docker_network_host, status, created_at, updated_at
`

type UpdateSiteHostPortParams struct {
	ID       uuid.UUID   `json:"id"`
	HostPort pgtype.Int4 `json:"host_port"`
}

func (q *Queries) UpdateSiteHostPort(ctx context.Context, arg UpdateSiteHostPortParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSiteHostPort, arg.ID, arg.HostPort)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PrimaryUrl,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.DockerfilePath,
		&i.BuildContext,
		&i.ContainerPort,
		&i.HostPort,
		&i.NginxSslEnabled,
		&i.NginxForceHttps,
		&i.SiteType,
		&i.DockerVolumeMounts,
		&i.DockerNamedVolumes,
		&i.DockerNetworkHost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteStatus = `-- name: UpdateSiteStatus :one
UPDATE sites SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, name, slug, primary_url, git_repo_url, git_branch, dockerfile_path, build_context, container_port, host_port, nginx_ssl_enabled, nginx_force_https, site_type, docker_volume_mounts, docker_named_volumes, docker_network_host, status, created_at, updated_at
`

type UpdateSiteStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSiteStatus(ctx context.Context, arg UpdateSiteStatusParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSiteStatus, arg.ID, arg.Status)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.PrimaryUrl,
		&i.GitRepoUrl,
		&i.GitBranch,
		&i.DockerfilePath,
		&i.BuildContext,
		&i.ContainerPort,
		&i.HostPort,
		&i.NginxSslEnabled,
		&i.NginxForceHttps,
		&i.SiteType,
		&i.DockerVolumeMounts,
		&i.DockerNamedVolumes,
		&i.DockerNetworkHost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
