// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_secrets.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteSiteSecret = `-- name: DeleteSiteSecret :exec
DELETE FROM site_secrets WHERE site_id = $1 AND key = $2
`

type DeleteSiteSecretParams struct {
	SiteID uuid.UUID `json:"site_id"`
	Key    string    `json:"key"`
}

func (q *Queries) DeleteSiteSecret(ctx context.Context, arg DeleteSiteSecretParams) error {
	_, err := q.db.Exec(ctx, deleteSiteSecret, arg.SiteID, arg.Key)
	return err
}

const getSiteSecret = `-- name: GetSiteSecret :one
SELECT id, site_id, key, encrypted_value, created_at, updated_at FROM site_secrets WHERE site_id = $1 AND key = $2
`

type GetSiteSecretParams struct {
	SiteID uuid.UUID `json:"site_id"`
	Key    string    `json:"key"`
}

func (q *Queries) GetSiteSecret(ctx context.Context, arg GetSiteSecretParams) (SiteSecret, error) {
	row := q.db.QueryRow(ctx, getSiteSecret, arg.SiteID, arg.Key)
	var i SiteSecret
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Key,
		&i.EncryptedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSiteSecrets = `-- name: ListSiteSecrets :many
SELECT id, site_id, key, created_at, updated_at FROM site_secrets WHERE site_id = $1 ORDER BY key ASC
`

type ListSiteSecretsRow struct {
	ID        uuid.UUID `json:"id"`
	SiteID    uuid.UUID `json:"site_id"`
	Key       string    `json:"key"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListSiteSecrets(ctx context.Context, siteID uuid.UUID) ([]ListSiteSecretsRow, error) {
	rows, err := q.db.Query(ctx, listSiteSecrets, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiteSecretsRow{}
	for rows.Next() {
		var i ListSiteSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Key,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSiteSecret = `-- name: UpsertSiteSecret :one
INSERT INTO site_secrets (site_id, key, encrypted_value)
VALUES ($1, $2, $3)
ON CONFLICT (site_id, key) DO UPDATE SET
    encrypted_value = EXCLUDED.encrypted_value,
    updated_at = now()
RETURNING id, site_id, key, created_at, updated_at
`

type UpsertSiteSecretParams struct {
	SiteID         uuid.UUID `json:"site_id"`
	Key            string    `json:"key"`
	EncryptedValue []byte    `json:"encrypted_value"`
}

type UpsertSiteSecretRow struct {
	ID        uuid.UUID `json:"id"`
	SiteID    uuid.UUID `json:"site_id"`
	Key       string    `json:"key"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpsertSiteSecret(ctx context.Context, arg UpsertSiteSecretParams) (UpsertSiteSecretRow, error) {
	row := q.db.QueryRow(ctx, upsertSiteSecret, arg.SiteID, arg.Key, arg.EncryptedValue)
	var i UpsertSiteSecretRow
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Key,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
